### ISSUE TITLE
Non-default WORKING_DIRECTORY does not work for local java applications

### ISSUE THREAD

**Issue by zerovox** [kukido/eclipser#14]
The org.eclipse.jdt.launching.WORKING_DIRECTORY attribute isn't used when creating JavaConfigurations, instead a default value is always used.

I think this is a pretty easy fix, I had a go(the code changes were a couple of lines I'm pretty sure) but the project doesn't have any sort of build so I didn't have the required jars to make it work. Would be cool if you could gradleify this or at least check in the four required jars.

**Comment by kukido** [comment]
Hi zerovox,
Thank you for your interest in the plugin! 
I have included required jars into the project. Once you pull the project, you will have to redefine only IntelliJ Platform Plugin SDK. Let me know if you have any other questions.
Looking forward to your pull request!

**Comment by kukido** [comment]
Eclipser 0.7.0 was published to a repository. Please check it out.
