### ISSUE TITLE
Plugin "Eclipse" was not loaded: required plugin "Ant Support" not installed.

### ISSUE THREAD

**Issue by DavePilks** [kukido/eclipser#17]
After updating Android Studio, I get this error after I re-install Eclipser. And I cant fin this "AntSupprt" plugin in the repo. Am I missing something?

**Comment by kukido** [comment]
It seems that Android Studio does not have Ant support, even though it is based on IntelliJ platform. I'll have a look on how to make Ant support optional.

**Comment by kukido** [comment]
Per Android portal [documentation](http://developer.android.com/tools/building/building-cmdline-ant.html) Ant was replaced with Gradle as the build tool. I guess that's why Ant support was dropped from Android Studio.

**Comment by kukido** [comment]
I tried to add Ant plugin to Android Studio and unfortunately not succeeded. I'm going to remove Android Studio support from future version of Eclipser to provide consistent experience. Sorry about that.
