### ISSUE TITLE
Add support for launchConfiguration type = "org.eclipse.pde.ui.RuntimeWorkbench"

### ISSUE THREAD

**Issue by otopba** [kukido/eclipser#18]
Please add support for type "org.eclipse.pde.ui.RuntimeWorkbench"

**Comment by kukido** [comment]
This request is a duplicate of #15. 
`RuntimeWorkbench` is Eclipse application itself. There's no Eclipse runner in IntelliJ for obvious reasons, hence the plugin does not support this kind of launchers.
