### ISSUE TITLE
Launch Eclipse Application Product

### ISSUE THREAD

**Issue by ankitbhavsar** [kukido/eclipser#19]
Hello Team,

I was trying to migrate from eclipse and attempted to convert using eclipser but faced below error message.
"Unsupported configuration type: org.eclipse.pde.ui.RuntimeWorkbench".

Is there any way to fix this ??

Thanks,
Ankit Bhavsar

**Comment by kukido** [comment]
Hi Ankit,
RuntimeWorkbench configuration will not be supported, as it is launch of Eclipse itself, and IntelliJ does not have run configuration of that type. While it is most likely doable with a custom IntelliJ run configuration, it is not worth development in terms of value/effort.
Cheers,
Andrey
