### ISSUE TITLE
Sync launch configs rather than converting

### ISSUE THREAD

**Issue by bemace** [kukido/eclipser#22]
It'd be really nice if it could convert the Eclipse launch configs at run time so that I pick up any changes by Eclipse users automatically. Or maybe link IntelliJ configs to Eclipse configs and re-convert when the Eclipse configs change. And perhaps write a new Eclipse launch config when the IntelliJ config is saved?

Does that look like it will be possible in later releases?

**Comment by kukido** [comment]
It is definitely possible, I believe you can set a file change watch and then add an even handler to update the configuration. 

The one-way sync is definitely easier, as one does not have to worry about Eclipse compatibility. With two-way sync things are getting more complex, as Eclipse documentation is very sparse, so one has to spent a lot of time experimenting with converting from IntelliJ configuration to Eclipse launch files.

At this time I'm not using Eclipser at work or for personal projects and not planning on adding this feature anytime soon, if ever. 

Feel free to either submit a pull request or fork the repo and make it work for yourself.
