### ISSUE TITLE
The plugin breaks navigation in pom.xml in IDEA 2019.3 EAP

### ISSUE THREAD

**Issue by garlikus** [kukido/eclipser#32]
The navigation in pom.xml, e.g. navigating to dependency declaration, property declaration, etc., doesn't work with the eclipser installed. 2019.3 EAP is affected. It used to work in previoues IDEA versions.

Please refer to issue reported in IDEA tracker: https://youtrack.jetbrains.com/issue/IDEA-224565

**Comment by xinkunZ** [comment]
Same issue here!!!
I was think it is IDEA's bug, but I am wrong, I have try many times, and find it is blame to this plugin at last!!!

**Comment by xinkunZ** [comment]
Also, this plugin break spring xml based check in IDEA 2019.3 too

**Comment by mr-rycho** [comment]
Confirmed on idea community 2019.3.2 (193.6015.39) + eclipser 0.7.1 . When I disable the plugin and restart idea everything works as expected.

**Comment by petr-nehez** [comment]
Same here - I can now start using 2019.3 (https://youtrack.jetbrains.com/issue/IDEA-228110#focus=streamItem-27-3910331.0-0).

**Comment by vaurat** [comment]
Confirmed : xml Spring files and Ant xml files now readable in IDEA 2019.3+ Only if Eclipser is disabled.

**Comment by CichyBart** [comment]
Confirmed on 2019.3.2 Community Edition and eclipser 0.7.1.

**Comment by AHuzichenko** [comment]
The same issue. And can not extract properties with shortcut as well.
https://youtrack.jetbrains.com/issue/IDEA-231443?replyTo=27-3918114
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39

**Comment by pidzama** [comment]
> Confirmed on 2019.3.2 Community Edition and eclipser 0.7.1.

Same here.

**Comment by SBA-LBC** [comment]
So when is this expected to be fixed? In my view, Disabling the plugin is Kinda temporary solution though :)

**Comment by kukido** [comment]
I need to look into updated IntelliJ API to estimate the effort of making it work.

**Comment by kukido** [comment]
If anyone has a pull request to fix it, I'm happy to review, merge and release the updated plugin.

**Comment by krasa** [comment]
Adding `implements DomSupportEnabled` to `EclipserFileType` would probably fix everything.

**Comment by kukido** [comment]
The changes were merged and new version of the plugin is published.
https://plugins.jetbrains.com/plugin/7153-eclipser/versions/stable/92473
