### ISSUE TITLE
 Cannot find Eclipser from MarketPlace in Intellij Ultimate Edition 2021.1

### ISSUE THREAD

**Issue by greyshine** [kukido/eclipser#40]
Hello Andrey,

I just found the same issue for current IntelliJ version as mentioned in ticket #36.

I gave it a quick try in the code if it depends on some setting ;-)
Well, it looks more complicated than I thought. Respect.

Could you help out here?

Since I did not find it in the Jetbrains marketplace I downloaded current version Eclipser-0.8.7.
But it is not accepted by IntelliJ.

Best greetings from Germany
Dirk

**Comment by Root-2k** [comment]
I modified the build.gradle file (for testing purpose) by updating the following properties: 

- intellij version: 'IC-2021.1'
- patchPluginXml untilBuild: '211.*'
- version '0.8.8'

I've got some warnings, but the build was completed and the plugin seems to work.
Tested with 2021.1 Community Edition; Build #IC-211.6693.111

> WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
Starting searchable options index builder
WARN - tor.impl.FontFamilyServiceImpl - Couldn't access required runtime API, will fall back to basic logic of font selection 
WARN - options.ex.ConfigurableWrapper - Cannot find extension point com.intellij.compilerSettingsFactory in ProjectDefault (Template) Project 
WARN - #com.intellij.ui.jcef.JBCefApp - JCEF is manually disabled in headless env via 'ide.browser.jcef.headless.enabled=false'

**Comment by omzer** [comment]
> I modified the build.gradle file (for testing purpose) by updating the following properties:
> 
> * intellij version: 'IC-2021.1'
> * patchPluginXml untilBuild: '211.*'
> * version '0.8.8'
> 
> I've got some warnings, but the build was completed and the plugin seems to work.
> Tested with 2021.1 Community Edition; Build #IC-211.6693.111
> 
> > WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options
> > Starting searchable options index builder
> > WARN - tor.impl.FontFamilyServiceImpl - Couldn't access required runtime API, will fall back to basic logic of font selection
> > WARN - options.ex.ConfigurableWrapper - Cannot find extension point com.intellij.compilerSettingsFactory in ProjectDefault (Template) Project
> > WARN - #com.intellij.ui.jcef.JBCefApp - JCEF is manually disabled in headless env via 'ide.browser.jcef.headless.enabled=false'

Where can I find the path to build.gradle file?

**Comment by schaitl** [comment]
> 
> 
> > I modified the build.gradle file (for testing purpose) by updating the following properties:
> > 
> > * intellij version: 'IC-2021.1'
> > * patchPluginXml untilBuild: '211.*'
> > * version '0.8.8'
> > 
> > I've got some warnings, but the build was completed and the plugin seems to work.
> > Tested with 2021.1 Community Edition; Build #IC-211.6693.111
> > > WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options
> > > Starting searchable options index builder
> > > WARN - tor.impl.FontFamilyServiceImpl - Couldn't access required runtime API, will fall back to basic logic of font selection
> > > WARN - options.ex.ConfigurableWrapper - Cannot find extension point com.intellij.compilerSettingsFactory in ProjectDefault (Template) Project
> > > WARN - #com.intellij.ui.jcef.JBCefApp - JCEF is manually disabled in headless env via 'ide.browser.jcef.headless.enabled=false'
> 
> Where can I find the path to build.gradle file? @Root-2k

@omzer It's right in the root directory of the repository.

**Comment by omzer** [comment]
@schaitl Thanks! but how can I convert it to JAR so I can import it on intellij?

**Comment by schaitl** [comment]
> @schaitl Thanks! but how can I convert it to JAR so I can import it on intellij?

You should import this project into IntelliJ, apply the mentioned fix(es), and then run the gradle-goal `buildPlugin`. This will build the plugin jar and put it into the folder `build/lib`.
The goal `runIde` can be used to start a ("child") IntelliJ IDE where the plugin is loaded and can be tested/debugged.

**Comment by Root-2k** [comment]
I used the command 'gradlew build' within the root directory and imported the generated ZIP file (folder 'build/distributions') in IntelliJ (Settings > Plugins -> Install Plugin from Disk... (option in cog).

**Comment by kukido** [comment]
I will take care of the new build today. Can't figure out a way to configure plugin to be compatible with future IntelliJ releases, so have to publish for each new release.

**Comment by greyshine** [comment]
Thank you all for your efforts! Thank you kukido for your feedback.  
Y'all keep well and fit !

**Comment by schaitl** [comment]
> 
> 
> I will take care of the new build today. Can't figure out a way to configure plugin to be compatible with future IntelliJ releases, so have to publish for each new release.

I actually removed the whole `patchPluginXml {...}` section in the `build.gradle` and it seemed to work fine. From my understanding it only breaks once the API supplied by IntelliJ itself changes... I'm no expert in IntelliJ plugin development though.

**Comment by kukido** [comment]
Should be available now in the repository. Took me a bit longer, as I tried to upgrade Gradle as well, will do it later.
