### ISSUE TITLE
Plugin 'Eclipser' v0.8.8 is not compatible with IntelliJ 2021.2

### ISSUE THREAD

**Issue by priyankakalra** [kukido/eclipser#42]
Hi,

Eclipser plugin v0.8.8 has stopped working with IntelliJ 2021.2 (Build: 212.4746.92) and gives the below message:

Plugin error: Plugin 'Eclipser' (version '0.8.8') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92

**Comment by kukido** [comment]
The newer version of the plugin is uploaded to the plugins repository.
