### ISSUE TITLE
Support IntelliJ 2022.2

### ISSUE THREAD

**Issue by AB-xdev** [kukido/eclipser#49]
At first, let me thank you for the great plugin 😄 

However Eclipser doesn't seem to be compatible with IntelliJ 2022.2 yet.
![grafik](https://user-images.githubusercontent.com/45384811/182093025-2cacd9e1-470c-4d94-af47-06333f0c67dc.png)

**Comment by b1tc4b** [comment]
I forked the repo and bumped the versions -> https://github.com/b1tc4b/eclipser

Just clone and build it (>JDK11)
./gradlew buildPlugin

After the build you will find a zip file in "build/distributions" which can be installed in recent IntelliJ versions.

Maybe this helps someone else...

cheers

**Comment by kukido** [comment]
Will take care of it today.

**Comment by TTia** [comment]
Hello @kukido, -again thanks for the great utility-. Do you have any update about it? Many thanks!

**Comment by kukido** [comment]
It was uploaded. Please have a look.

**Comment by TTia** [comment]
Now it's available, many thanks!
