### ISSUE TITLE
Support for Intellij 2022.2.1

### ISSUE THREAD

**Issue by adben** [kukido/eclipser#50]
With the last release of intellij(build IU-222.3739.54) the plugin does not works, any plans for updates?

**Comment by b1tc4b** [comment]
I forked the repo and bumped the versions -> https://github.com/b1tc4b/eclipser

Just clone and build it (>JDK11)
`./gradlew buildPlugin`

After the build you will find a zip file in "build/distributions" which can be installed in recent IntelliJ versions.

Maybe this helps someone else...

cheers

**Comment by kukido** [comment]
Will take care of it today.

**Comment by kukido** [comment]
@b1tc4b Thank you for the patch, it was merged and the plugin was uploaded. 🎉

**Comment by simoliva-sunny** [comment]
Hi @kukido , any plans to support Intellij Idea version 233.14475.28 ?
