### ISSUE TITLE
Update for IntelliJ 2022.3?

### ISSUE THREAD

**Issue by cmirza-esi** [kukido/eclipser#53]
Hi, seems like the plugin doesn't work with the latest version of IntelliJ (build IU-223.7571.182). Any plans for an update to this version?

**Comment by jakwarrior** [comment]
I forked the fork of @Leonbabylon, and I made two releases : 0.9.3 for Intellij 2022.3 and 0.9.4 for Intellij 2023.1
https://github.com/jakwarrior/eclipser/releases

**Comment by kukido** [comment]
It is available now.
https://plugins.jetbrains.com/plugin/7153-eclipser/versions/stable/415276
