### ISSUE TITLE
Support  Intellij Idea version 233.14475.28 

### ISSUE THREAD

**Issue by simoliva-sunny** [kukido/eclipser#59]
Hi, are there any plans to support Intellij Idea version 233.14475.28 ?

**Comment by sumant4ssm** [comment]
Please add support for Build #IU-233.14475.28.

**Comment by sumant4ssm** [comment]
> Hi, are there any plans to support Intellij Idea version 233.14475.28?

I have forked the original project and rebuilt it to support the latest version of Intellij. You can find the latest jar in the build folder.
https://github.com/sumant4ssm/eclipser

**Comment by kukido** [comment]
It was updated.
